<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-40TMDJ5" failures="1" tests="1" name="Default test(failed)" time="0.08" errors="0" timestamp="2022-11-03T21:14:57 IST">
  <testcase classname="testng.secondtestng" name="f1" time="0.012">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at testng.secondtestng.f1(secondtestng.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase classname="testng.secondtestng" name="f2" time="0.0">
    <ignored/>
  </testcase> <!-- f2 -->
</testsuite> <!-- Default test(failed) -->
